update pipeline

diff --git a/.github/workflows/security-workflow.yml b/.github/workflows/security-workflow.yml
--- a/.github/workflows/security-workflow.yml
+++ b/.github/workflows/security-workflow.yml
@@ -144,6 +144,10 @@ jobs:
     
     - name: Install dependencies
       run: |
+        # Create results directory
+        mkdir -p results/security
+
+        # Install analysis tools
         python -m pip install --upgrade pip
         pip install -r requirements.txt
     
@@ -171,12 +175,12 @@ jobs:
         quiet: false
         soft_fail: true
 
-    - name: Debug Checkov Results
-      run: |
-        echo "Checkov results file contents:"
-        cat results/security/${{ inputs.tool }}_checkov_results.json || echo "File not found"
-        echo "Directory contents:"
-        ls -l results/security
+    # - name: Debug Checkov Results
+    #   run: |
+    #     echo "Checkov results file contents:"
+    #     cat results/security/${{ inputs.tool }}_checkov_results.json || echo "File not found"
+    #     echo "Directory contents:"
+    #     ls -l results/security
 
     # - name: Run Checkov Security Scan
     #   run: |
